### ISSUE TITLE
Naming scheme of Tendrl collectd plugins

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/node-monitoring#20]
@anmolbabu Please explain naming scheme of Tendrl's collectd plugins, in efforts to standardize them, we should ensure the names convey their purpose and association with Tendrl and do not cause confusion with ceph, gluster, $sds specific collectd plugins

**Comment by r0h4n** [comment]
@anmolbabu any updates?

**Comment by anmolbabu** [comment]
So, the collectd plugins are named as per the following:

- All node specific plugins and generic plugins are named by the purpose they solve.
Note: As of now, the plugins under this category are readily packaged with collectd and we have not much control on it
ex:
1. handle_collectd_notification -- A generic plugin that pushes all collectd detected threshold breach notifications to node-agent exposed socket...

- All sds-specific plugins are named as <sds_name>_purpose
e.x: 
1. ceph_utilization.py -- Adds all ceph resource utilizations like cluster,pool and osd utilizations
2. ceph_cluster_iops -- Adds iops at ceph cluster level
3. ceph_node_network_throughput -- Adds n/w throughput(cluster and public) at node level for a ceph node
4. glusterfs_peer_network_throughput -- Adds n/w throughput(cluster) at node level for a gluster node
5. glusterfs_utilization -- Adds gluster resources utilizations like cluster and volume

**Comment by anmolbabu** [comment]
I agree with you that their association with tendrl might need to made specific as the plugins use tendrl generated ids making them specific to tendrl and hence making it necessary to build its association with tendrl. I'll write a refactoring PR for this once all the dashboards are complete...

**Comment by r0h4n** [comment]
ok, link to this issue when you have the PR

**Comment by anmolbabu** [comment]
@r0h4n Can you please close this as this has been fixed as part of https://github.com/Tendrl/node-monitoring/pull/31/commits/6c3565a1c164d62c453ddda4d4ca3d19254f5c2f
